### ISSUE TITLE
view switcher missing for logged-in user

### ISSUE THREAD

**Issue by judell** [hypothesis/pdf.js-hypothes.is#13]
# Steps to reproduce:

1. Follow the README setup for this repo

2. Load http://localhost:8000

# Bad behavior

When logged in, the view switcher vanishes and the console says:

```
console.js:26 Error connecting to H push notification service
...
Received a broken close frame containing a reserved status code.
```

![image](https://user-images.githubusercontent.com/46509/27891613-9e68bea4-61af-11e7-89cf-1b5963412a92.png)

**Comment by robertknight** [comment]
I'm not quite sure what "view switcher" refers to (the group selector?) but everything worked as expected when I last tested this repo a few months ago, so I'm going to close this issue for now.
