### ISSUE TITLE
Upgrade PDF.js to the latest v2.x release

### ISSUE THREAD

**Issue by robertknight** [hypothesis/pdf.js-hypothes.is#15]
This repository currently has a version of PDF.js that is several years old. We are updating our other PDF annotation environments to the latest v2.x release ([see tracking issue](https://github.com/hypothesis/product-backlog/issues/1062)) and we should update this repository as well.

On a related note, it might be worth considering turning this repo into an npm package so it is easier for consumers to update. We could potentially also statically host the HTML as a convenience.

**Comment by asmecher** [comment]
+1, we would love to see this repo updated! We [reference the changes in this repo](https://github.com/asmecher/hypothesis/blob/5fb429add34fca45b9c9defa957e7f270413149d/README#L41) for our OJS integration, but newer versions of PDF.js are no longer compatible.

**Comment by Jdtercero** [comment]
Would be really great, if we could count with newest  hypothesis' patch. The actual is not working with the newest PDF.js over OJS

**Comment by asmecher** [comment]
Hi all! I'm very happy to see some progress on this (https://github.com/hypothesis/pdf.js-hypothes.is/pull/17) -- what is the status of the update? Is that work completed now?

**Comment by robertknight** [comment]
Yes. This is done. You can see the current version of PDF.js in the browser console when the viewer loads.

**Comment by asmecher** [comment]
:+1: Many thanks, @robertknight! With the old version, there was a single commit that contained the changes that convert a stock PDF.js installation to one supporting Hypothes.is. Is that still the case? If so, could you point me toward the new equivalent commit?

**Comment by robertknight** [comment]
There is a script in the “tools” directory which will fetch the latest PDF.js release and apply the changes needed to add Hypothesis.
