### ISSUE TITLE
Multiple Iframes - Sidebars Don't Work Properly

### ISSUE THREAD

**Issue by tgiardina** [hypothesis/pdf.js-hypothes.is#20]
# Issue

If you embed two PDFs using iframes on the same page a la 
```
<html>
  <body>
    <iframe style="width:100%" height="600" src="/viewer/web/viewer.html?file=/demo.pdf"></iframe>
    <iframe style="width:100%" height="600" src="/viewer/web/viewer.html?file=/demo1.pdf"></iframe>
  </body>
</html>
```
the sidebars don't work correctly. In particular, the first sidebar won't include any annotations and the second sidebar will include the annotations of both PDFs.

# Steps to Reproduce

1. Clone the `two-iframes-bug` branch of [my repo](https://github.com/tgiardina/containerized-hypothesis/tree/two-iframes-bug)
2. Run `make deploy`
3. Navigate to `localhost` (or `localhost:80`)

**Comment by robertknight** [comment]
Thanks for the report. This is a known issue with the Hypothesis client. See https://github.com/hypothesis/client/issues/249 and https://github.com/hypothesis/client/issues/187. I don't have a convenient workaround to share at the moment.

**Comment by tgiardina** [comment]
Thanks for the reply @robertknight! Seeing how the most recent issue was opened three years ago, I'm assuming fixing this bug isn't a priority, correct? It does look like you did some research into it, though. By your estimate, is it something I could fix in a week or so?

**Comment by klemay** [comment]
From a product perspective I can say this isn't a near-term priority for us. It's in our "Medium term" column on our bug backlog, meaning we might pick this up in a few months if other more urgent bugs don't get in front of it.

**Comment by tgiardina** [comment]
Thanks for the info, @klemay! Do you have an estimate for how long it would take to fix?

For context, my current situation is that I'm wrapping up a contract over the next few weeks, and one of my deliverables is blocked by this bug. I need to decide whether I should
- Attempt a PR, or
- Punt on the deliverable.
Any info on how difficult this bug will be to squash would be greatly appreciated!

**Comment by robertknight** [comment]
Hi @tgiardina,

I think fixing this is going to involve revisiting the fundamentals of how the sidebar finds the frames in the tab which contain content that can be annotated. This is not trivial, so unless you want to get deep into the code that does this, I'd suggest punting on the deliverable.

The code that connects the sidebar with content that can be annotated lives in `discovery.js`, see https://github.com/hypothesis/client/blob/d90a45191f8c44ba7a4e83e64036d3b79b096ac8/src/shared/discovery.js. The problem right now is that it is assumed that there is only one "server" (sidebar) in the browser tab and possibly many "clients" (frames that can be annotated). The current approach allows for "client" and "server" frames to be anywhere in the hierarchy of frames on a page. I think a better approach would take advantage of the fact that in practice, this flexibility is never used and the actual relationship is either:

```
[ Frame where Hypothesis is loaded, and with content that can be annotated ]
   |- [ Sidebar iframe ]
```

Or:

```
[ Frame where Hypothesis is loaded ]
  |- [ Sidebar iframe ]
  |- [ Iframe with content that can be annotated ]
```

**Comment by robertknight** [comment]
This issue has now been fixed in the client as part of a larger reworking of how the different frames in the client communicate.
