### ISSUE TITLE
Not working in iframe anymore ?

### ISSUE THREAD

**Issue by f2boot** [hypothesis/pdf.js-hypothes.is#22]
I have updated my code since the merging of pull request #21 and now, **when viewing in an iframe**, I can't get the hypothes.is layer over the pdf.js any more  (it is fine when opening the viewer in the main window)

It looks like pdfjs-init.js is properly injected but does not fire the injection of embed.js

Any clue ?

Thanks

**Comment by f2boot** [comment]
A hint (and solution ?) may be:
pdf.js/viewer/web/viewer.js has changed since previous version.

In previous version, we used to have 
function webViewerLoad() {
[...]
  var event = document.createEvent('CustomEvent');
  event.initCustomEvent('webviewerloaded', true, true, {});
  document.dispatchEvent(event);
[...]
}
around line 254

and now we have 
function webViewerLoad() {
[...]
  var event = document.createEvent("CustomEvent");
  event.initCustomEvent("webviewerloaded", true, true, {
    source: window
  });

  try {
    parent.document.dispatchEvent(event);
  } catch (ex) {
    console.error("webviewerloaded: ".concat(ex));
    document.dispatchEvent(event);
  }

around line 20442
this means 
    document.dispatchEvent(event); 
only runs if     
parent.document.dispatchEvent(event);
has failed, which is not always the case when we are in iframe...
therefore, the script in pdf-init.js was not running

At this time, i have just added
    document.dispatchEvent(event);
under
    parent.document.dispatchEvent(event);
in the "try"

It is working but I do not know if it is a proper solution

**Comment by robertknight** [comment]
There was a change in PDF.js when the viewer is loaded into an iframe with a same-origin parent. For the https://via.hypothes.is service we have a workaround at https://github.com/hypothesis/via/blob/0fef53e973215907b5fa4b429b3eae3002593489/via/static/js/pdfjs-init.js#L8. It looks like we need to update the pdfjs-init.js file in this repository too.

**Comment by f2boot** [comment]
Now working as expected Many thanks :)
