### ISSUE TITLE
Update the packaged PDF.js version

### ISSUE THREAD

**Issue by csillag** [hypothesis/pdf.js-hypothes.is#3]
When https://github.com/hypothesis/h/pull/1775 is merged (and deployed), we will be able to update the packaged PDF.js version to [v1.0.907](https://github.com/mozilla/pdf.js/releases/tag/v1.0.907), which has some nice improvements.

**Comment by BigBlueHat** [comment]
This one's ongoing, so closing. Thanks!

**Comment by ste-m5s** [comment]
I think this need to be updated again
