### ISSUE TITLE
Ensuring everyone annotates same PDF

### ISSUE THREAD

**Issue by jgmac1106** [hypothesis/pdf.js-hypothes.is#5]
What strategies have folks developed to ensure readers are annotating the same PDF? For example if I am using a locally hosted file but someone else finds the article at a library how do we see each other's annotations?

Right now I am thinking I just link directly to a file and say, "use this one" but I am wondering long term can things such as DOI be used to identify PDFs regardless of where they are hosted?

**Comment by csillag** [comment]
For now, we are using PDF fingerprint.
2015.03.29. 17:05 ezt írta ("jgmac1106" <notifications@github.com>):

**Comment by dwhly** [comment]
There are two possible scenarios here.

If the PDF is actually the same, but simply hosted locally, we will already know they are the same.  Annotations on one will show up on the other.  Try it yourself.  Send someone a PDF by email.  Drag it into chrome.  The two of you will be able to collaboratively annotate in real time.

The other scenario is if the content is the same, but the PDF's fingerprint is different in some way.  Long term it may make sense for folks to be able to assert equivalence between two documents.  (PDF and HTML for instance).

**Comment by jgmac1106** [comment]
You folks rock. @dwhly it worked flawlessly.
