### ISSUE TITLE
Where does the call to "https://hypothes.is/api/search" happens

### ISSUE THREAD

**Issue by sulthanallaudeen** [hypothesis/pdf.js-hypothes.is#7]
I am trying to customize the pdf.js-hypothesis.is

I wanted to do some additional calls in it, where i will add some parameter, i can notice that this call happens to fetch the annotations made by users in the pdf.. 

https://hypothes.is/api/search?limit=200&offset=0&order=asc&sort=created&uri=

So, May i know where does this call happens ? 

Note : I downloaded code from the latest master

Thanks

**Comment by sulthanallaudeen** [comment]
I can able to open podf like ths..

http://192.168.1.58/annotate/hypothesis/viewer/web/viewer.html?file=lara.pdf

But how can i save the annotation.. 

I can see the network request like this

https://hypothes.is/api/annotations

But i can't able to find where does the request was performed.. 

May i know the place where that was being sent, or
May i have any wiki.. ? 

So that i can customize this one according to my need.

**Comment by BigBlueHat** [comment]
@sulthanallaudeen sorry for the slow reply!

The project you'll need to customize is known as [h](http://github.com/hypothesis/h). This project simply ties a self-hosted PDF.js Viewer to the Hypothesis Public Service which lives at http://hypothes.is/

You'd need to customize and host `h` to fully control the annotation experience.

I hope that helps!
